"""Initial migration.

Revision ID: 008f48917cad
Revises: c1d58cfcce94
Create Date: 2024-06-15 17:17:30.354771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008f48917cad'
down_revision = 'c1d58cfcce94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=30), nullable=True))
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_surname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_surname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
