"""Initial migration.

Revision ID: 31b9514dd062
Revises: 008f48917cad
Create Date: 2024-06-15 18:48:57.754449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b9514dd062'
down_revision = '008f48917cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('book_warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('book_warehouses', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
