"""Initial migration.

Revision ID: 57188cc9f37c
Revises: 6f5152579f60
Create Date: 2024-06-17 11:41:43.984841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57188cc9f37c'
down_revision = '6f5152579f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
