"""Initial migration.

Revision ID: 6f5152579f60
Revises: 31b9514dd062
Create Date: 2024-06-16 17:30:17.461100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f5152579f60'
down_revision = '31b9514dd062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
