"""Initial migration.

Revision ID: 8f8d43352594
Revises: 9b5d1374a648
Create Date: 2024-06-15 09:50:06.688306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8d43352594'
down_revision = '9b5d1374a648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_name', sa.String(length=30), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_name', sa.String(length=30), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('publisher_name')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('genre_name')

    # ### end Alembic commands ###
