"""Initial migration.

Revision ID: 9b5d1374a648
Revises: 0a1b5a02e5fb
Create Date: 2024-06-15 09:35:27.154628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5d1374a648'
down_revision = '0a1b5a02e5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
